### ISSUE TITLE
Can this be fitted to any NEMA 23 stepper?

### ISSUE THREAD

**Issue by daxliniere** [makerbase-mks/MKS-SERVO57A#6]
Can this be fitted to any NEMA 23 stepper?
Thanks,
Dax.

**Comment by kutukvpavel** [comment]
With *a* NEMA23 motor, yes, absolutely. The number 57 refers to 57mm, which is the characteristic dimension for NEMA23 flanges. So, in fact, this was made to be retrofitted on NEMA23 steppers. I've done so several times.

With *any* NEMA23 stepper motor? Of course, there are some obvious limitations due to the use of a magnet glued onto the back of the shaft. The magnet (being diametrically magnetized) serves as encoder reference and is essential for this driver design to operate. Some steppers have no hole on the back cover (so, they don't expose the shaft from the back), some are biaxial, some have a hollow shaft etc. All of the aforementioned steppers can not be used with this driver (at least out-of-the-box).

Fun fact, until servo57 became readily available in AliExpress, I used to make custom mounting plates for Servo42 (meant to be used with NEMA17 steppers) drivers to be mounted on NEMA23. Right now I am mounting a Servo57 onto a NEMA52 (granted, such a large motor will be limited by 3A max current of this driver, but I have my reasons). So, almost everything is possible with a little engineering effort :). That's why I love drivers that use magnetic encoders.
